links:
- desc: Mon compte GitHub personnel
  title: Compte GitHub
  url: https://github.com/AmonKm
- desc: Wiki de techniques de pentest et de contournement
  title: HackTricks
  url: https://book.hacktricks.xyz
