links:
  - title: "Compte GitHub"
    desc: "Mon compte GitHub personnel"
    url: "https://github.com/AmonKm"
  - title: "HackTricks"
    desc: "Wiki hacking et sécurité offensive"
    url: "https://book.hacktricks.xyz"